# Generated by Django 4.2.5 on 2023-10-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_notified',
            field=models.BooleanField(db_comment='флаг отправки уведомления о производстве робота', default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_pending',
            field=models.BooleanField(db_comment='флаг ожидания заказа', default=False),
        ),
    ]
