# Generated by Django 4.2.5 on 2023-10-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_notified_order_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
